package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTimerCommandLog<M extends BaseTimerCommandLog<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 定时任务运行ID
	 */
	public void setTimerLogId(java.math.BigInteger timerLogId) {
		set("timer_log_id", timerLogId);
	}
	
	/**
	 * 定时任务运行ID
	 */
	public java.math.BigInteger getTimerLogId() {
		return get("timer_log_id");
	}

	/**
	 * 对应边界ID
	 */
	public void setBoundaryId(java.math.BigInteger boundaryId) {
		set("boundary_id", boundaryId);
	}
	
	/**
	 * 对应边界ID
	 */
	public java.math.BigInteger getBoundaryId() {
		return get("boundary_id");
	}

	/**
	 * 对应命令ID
	 */
	public void setCommandId(java.math.BigInteger commandId) {
		set("command_id", commandId);
	}
	
	/**
	 * 对应命令ID
	 */
	public java.math.BigInteger getCommandId() {
		return get("command_id");
	}

	/**
	 * 对应IP
	 */
	public void setIpAddress(java.lang.String ipAddress) {
		set("ip_address", ipAddress);
	}
	
	/**
	 * 对应IP
	 */
	public java.lang.String getIpAddress() {
		return getStr("ip_address");
	}

	/**
	 * 是否为白名单
	 */
	public void setIsWhite(java.lang.Integer isWhite) {
		set("is_white", isWhite);
	}
	
	/**
	 * 是否为白名单
	 */
	public java.lang.Integer getIsWhite() {
		return getInt("is_white");
	}

	/**
	 * 执行命令内容
	 */
	public void setCommandContent(java.lang.String commandContent) {
		set("command_content", commandContent);
	}
	
	/**
	 * 执行命令内容
	 */
	public java.lang.String getCommandContent() {
		return getStr("command_content");
	}

	/**
	 * 是否成功
	 */
	public void setIsSuccess(java.lang.Integer isSuccess) {
		set("is_success", isSuccess);
	}
	
	/**
	 * 是否成功
	 */
	public java.lang.Integer getIsSuccess() {
		return getInt("is_success");
	}

	/**
	 * 返回结果
	 */
	public void setCommandResult(java.lang.String commandResult) {
		set("command_result", commandResult);
	}
	
	/**
	 * 返回结果
	 */
	public java.lang.String getCommandResult() {
		return getStr("command_result");
	}

	/**
	 * 错误信息
	 */
	public void setErrMsg(java.lang.String errMsg) {
		set("err_msg", errMsg);
	}
	
	/**
	 * 错误信息
	 */
	public java.lang.String getErrMsg() {
		return getStr("err_msg");
	}

	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}

	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}

}
