package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTimerRunnerLog<M extends BaseTimerRunnerLog<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 对应定时任务
	 */
	public void setTimerId(java.math.BigInteger timerId) {
		set("timer_id", timerId);
	}
	
	/**
	 * 对应定时任务
	 */
	public java.math.BigInteger getTimerId() {
		return get("timer_id");
	}

	/**
	 * 抓取top5是否成功 0-不成功 1-成功
	 */
	public void setIsSuccess(java.lang.Integer isSuccess) {
		set("is_success", isSuccess);
	}
	
	/**
	 * 抓取top5是否成功 0-不成功 1-成功
	 */
	public java.lang.Integer getIsSuccess() {
		return getInt("is_success");
	}

	/**
	 * top5信息
	 */
	public void setTop5Info(java.lang.String top5Info) {
		set("top5_info", top5Info);
	}
	
	/**
	 * top5信息
	 */
	public java.lang.String getTop5Info() {
		return getStr("top5_info");
	}

	/**
	 * 待执行命令条数
	 */
	public void setCommandNumber(java.lang.Integer commandNumber) {
		set("command_number", commandNumber);
	}
	
	/**
	 * 待执行命令条数
	 */
	public java.lang.Integer getCommandNumber() {
		return getInt("command_number");
	}

	/**
	 * 执行命令成功条数
	 */
	public void setCommandSuccessNumber(java.lang.Integer commandSuccessNumber) {
		set("command_success_number", commandSuccessNumber);
	}
	
	/**
	 * 执行命令成功条数
	 */
	public java.lang.Integer getCommandSuccessNumber() {
		return getInt("command_success_number");
	}

	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}

	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}

}
