package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDbTable<M extends BaseDbTable<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public void setTableName(java.lang.String tableName) {
		set("TABLE_NAME", tableName);
	}
	
	public java.lang.String getTableName() {
		return getStr("TABLE_NAME");
	}

	public void setWhereVal(java.lang.String whereVal) {
		set("WHERE_VAL", whereVal);
	}
	
	public java.lang.String getWhereVal() {
		return getStr("WHERE_VAL");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public void setTableCount(java.lang.Long tableCount) {
		set("TABLE_COUNT", tableCount);
	}
	
	public java.lang.Long getTableCount() {
		return getLong("TABLE_COUNT");
	}

	public void setDateStr(java.lang.String dateStr) {
		set("DATE_STR", dateStr);
	}
	
	public java.lang.String getDateStr() {
		return getStr("DATE_STR");
	}

	public void setDbinfoId(java.lang.String dbinfoId) {
		set("DBINFO_ID", dbinfoId);
	}
	
	public java.lang.String getDbinfoId() {
		return getStr("DBINFO_ID");
	}

}
