package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHostInfo<M extends BaseHostInfo<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public void setIP(java.lang.String IP) {
		set("IP", IP);
	}
	
	public java.lang.String getIP() {
		return getStr("IP");
	}

	public void setPORT(java.lang.String PORT) {
		set("PORT", PORT);
	}
	
	public java.lang.String getPORT() {
		return getStr("PORT");
	}

	public void setROOT(java.lang.String ROOT) {
		set("ROOT", ROOT);
	}
	
	public java.lang.String getROOT() {
		return getStr("ROOT");
	}

	public void setPASSWD(java.lang.String PASSWD) {
		set("PASSWD", PASSWD);
	}
	
	public java.lang.String getPASSWD() {
		return getStr("PASSWD");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

}
