package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeskState<M extends BaseDeskState<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public void setHostName(java.lang.String hostName) {
		set("HOST_NAME", hostName);
	}
	
	public java.lang.String getHostName() {
		return getStr("HOST_NAME");
	}

	public void setFileStstem(java.lang.String fileStstem) {
		set("FILE_STSTEM", fileStstem);
	}
	
	public java.lang.String getFileStstem() {
		return getStr("FILE_STSTEM");
	}

	public void setSIZE(java.lang.String SIZE) {
		set("SIZE", SIZE);
	}
	
	public java.lang.String getSIZE() {
		return getStr("SIZE");
	}

	public void setUSED(java.lang.String USED) {
		set("USED", USED);
	}
	
	public java.lang.String getUSED() {
		return getStr("USED");
	}

	public void setAVAIL(java.lang.String AVAIL) {
		set("AVAIL", AVAIL);
	}
	
	public java.lang.String getAVAIL() {
		return getStr("AVAIL");
	}

	public void setUsePer(java.lang.String usePer) {
		set("USE_PER", usePer);
	}
	
	public java.lang.String getUsePer() {
		return getStr("USE_PER");
	}

	public void setDateStr(java.lang.String dateStr) {
		set("DATE_STR", dateStr);
	}
	
	public java.lang.String getDateStr() {
		return getStr("DATE_STR");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

}
