package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCpuState<M extends BaseCpuState<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public void setHostName(java.lang.String hostName) {
		set("HOST_NAME", hostName);
	}
	
	public java.lang.String getHostName() {
		return getStr("HOST_NAME");
	}

	public void setUSER(java.lang.String USER) {
		set("USER", USER);
	}
	
	public java.lang.String getUSER() {
		return getStr("USER");
	}

	public void setSYS(java.lang.Double SYS) {
		set("SYS", SYS);
	}
	
	public java.lang.Double getSYS() {
		return getDouble("SYS");
	}

	public void setIDLE(java.lang.Double IDLE) {
		set("IDLE", IDLE);
	}
	
	public java.lang.Double getIDLE() {
		return getDouble("IDLE");
	}

	public void setIOWAIT(java.lang.Double IOWAIT) {
		set("IOWAIT", IOWAIT);
	}
	
	public java.lang.Double getIOWAIT() {
		return getDouble("IOWAIT");
	}

	public void setIRQ(java.lang.String IRQ) {
		set("IRQ", IRQ);
	}
	
	public java.lang.String getIRQ() {
		return getStr("IRQ");
	}

	public void setSOFT(java.lang.String SOFT) {
		set("SOFT", SOFT);
	}
	
	public java.lang.String getSOFT() {
		return getStr("SOFT");
	}

	public void setDateStr(java.lang.String dateStr) {
		set("DATE_STR", dateStr);
	}
	
	public java.lang.String getDateStr() {
		return getStr("DATE_STR");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

}
