package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppState<M extends BaseAppState<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public void setAppInfoId(java.lang.String appInfoId) {
		set("APP_INFO_ID", appInfoId);
	}
	
	public java.lang.String getAppInfoId() {
		return getStr("APP_INFO_ID");
	}

	public void setCpuPer(java.lang.Double cpuPer) {
		set("CPU_PER", cpuPer);
	}
	
	public java.lang.Double getCpuPer() {
		return getDouble("CPU_PER");
	}

	public void setMemPer(java.lang.Double memPer) {
		set("MEM_PER", memPer);
	}
	
	public java.lang.Double getMemPer() {
		return getDouble("MEM_PER");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

}
