package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHeathMonitor<M extends BaseHeathMonitor<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public void setAppName(java.lang.String appName) {
		set("APP_NAME", appName);
	}
	
	public java.lang.String getAppName() {
		return getStr("APP_NAME");
	}

	public void setHeathUrl(java.lang.String heathUrl) {
		set("HEATH_URL", heathUrl);
	}
	
	public java.lang.String getHeathUrl() {
		return getStr("HEATH_URL");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setHeathStatus(java.lang.String heathStatus) {
		set("HEATH_STATUS", heathStatus);
	}
	
	public java.lang.String getHeathStatus() {
		return getStr("HEATH_STATUS");
	}

}
