package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTcpState<M extends BaseTcpState<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public void setHostName(java.lang.String hostName) {
		set("HOST_NAME", hostName);
	}
	
	public java.lang.String getHostName() {
		return getStr("HOST_NAME");
	}

	public void setACTIVE(java.lang.String ACTIVE) {
		set("ACTIVE", ACTIVE);
	}
	
	public java.lang.String getACTIVE() {
		return getStr("ACTIVE");
	}

	public void setPASSIVE(java.lang.String PASSIVE) {
		set("PASSIVE", PASSIVE);
	}
	
	public java.lang.String getPASSIVE() {
		return getStr("PASSIVE");
	}

	public void setRETRANS(java.lang.String RETRANS) {
		set("RETRANS", RETRANS);
	}
	
	public java.lang.String getRETRANS() {
		return getStr("RETRANS");
	}

	public void setDateStr(java.lang.String dateStr) {
		set("DATE_STR", dateStr);
	}
	
	public java.lang.String getDateStr() {
		return getStr("DATE_STR");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

}
