package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysLoadState<M extends BaseSysLoadState<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public void setHostName(java.lang.String hostName) {
		set("HOST_NAME", hostName);
	}
	
	public java.lang.String getHostName() {
		return getStr("HOST_NAME");
	}

	public void setOneLoad(java.lang.Double oneLoad) {
		set("ONE_LOAD", oneLoad);
	}
	
	public java.lang.Double getOneLoad() {
		return getDouble("ONE_LOAD");
	}

	public void setFiveLoad(java.lang.Double fiveLoad) {
		set("FIVE_LOAD", fiveLoad);
	}
	
	public java.lang.Double getFiveLoad() {
		return getDouble("FIVE_LOAD");
	}

	public void setFifteenLoad(java.lang.Double fifteenLoad) {
		set("FIFTEEN_LOAD", fifteenLoad);
	}
	
	public java.lang.Double getFifteenLoad() {
		return getDouble("FIFTEEN_LOAD");
	}

	public void setUSERS(java.lang.String USERS) {
		set("USERS", USERS);
	}
	
	public java.lang.String getUSERS() {
		return getStr("USERS");
	}

	public void setDateStr(java.lang.String dateStr) {
		set("DATE_STR", dateStr);
	}
	
	public java.lang.String getDateStr() {
		return getStr("DATE_STR");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

}
