package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMailSet<M extends BaseMailSet<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public void setSendMail(java.lang.String sendMail) {
		set("SEND_MAIL", sendMail);
	}
	
	public java.lang.String getSendMail() {
		return getStr("SEND_MAIL");
	}

	public void setFromMailName(java.lang.String fromMailName) {
		set("FROM_MAIL_NAME", fromMailName);
	}
	
	public java.lang.String getFromMailName() {
		return getStr("FROM_MAIL_NAME");
	}

	public void setFromPwd(java.lang.String fromPwd) {
		set("FROM_PWD", fromPwd);
	}
	
	public java.lang.String getFromPwd() {
		return getStr("FROM_PWD");
	}

	public void setSmtpHost(java.lang.String smtpHost) {
		set("SMTP_HOST", smtpHost);
	}
	
	public java.lang.String getSmtpHost() {
		return getStr("SMTP_HOST");
	}

	public void setSmtpPort(java.lang.String smtpPort) {
		set("SMTP_PORT", smtpPort);
	}
	
	public java.lang.String getSmtpPort() {
		return getStr("SMTP_PORT");
	}

	public void setSmtpSsl(java.lang.String smtpSsl) {
		set("SMTP_SSL", smtpSsl);
	}
	
	public java.lang.String getSmtpSsl() {
		return getStr("SMTP_SSL");
	}

	public void setToMail(java.lang.String toMail) {
		set("TO_MAIL", toMail);
	}
	
	public java.lang.String getToMail() {
		return getStr("TO_MAIL");
	}

	public void setCpuPer(java.lang.String cpuPer) {
		set("CPU_PER", cpuPer);
	}
	
	public java.lang.String getCpuPer() {
		return getStr("CPU_PER");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setMemPer(java.lang.String memPer) {
		set("MEM_PER", memPer);
	}
	
	public java.lang.String getMemPer() {
		return getStr("MEM_PER");
	}

	public void setHeathPer(java.lang.String heathPer) {
		set("HEATH_PER", heathPer);
	}
	
	public java.lang.String getHeathPer() {
		return getStr("HEATH_PER");
	}

}
