package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 用户名称
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	/**
	 * 用户名称
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * 登录账号
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	/**
	 * 登录账号
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}

	/**
	 * 登录密码 sha1加密
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 登录密码 sha1加密
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 是否为超级管理员
	 */
	public void setIsSuper(java.lang.Integer isSuper) {
		set("is_super", isSuper);
	}
	
	/**
	 * 是否为超级管理员
	 */
	public java.lang.Integer getIsSuper() {
		return getInt("is_super");
	}

	/**
	 * 角色
	 */
	public void setRole(java.lang.Integer role) {
		set("role", role);
	}
	
	/**
	 * 角色
	 */
	public java.lang.Integer getRole() {
		return getInt("role");
	}

	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}

	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}

}
