package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIntrusionInfo<M extends BaseIntrusionInfo<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public void setHostName(java.lang.String hostName) {
		set("HOST_NAME", hostName);
	}
	
	public java.lang.String getHostName() {
		return getStr("HOST_NAME");
	}

	public void setLSMOD(java.lang.String LSMOD) {
		set("LSMOD", LSMOD);
	}
	
	public java.lang.String getLSMOD() {
		return getStr("LSMOD");
	}

	public void setPasswdInfo(java.lang.String passwdInfo) {
		set("PASSWD_INFO", passwdInfo);
	}
	
	public java.lang.String getPasswdInfo() {
		return getStr("PASSWD_INFO");
	}

	public void setCRONTAB(java.lang.String CRONTAB) {
		set("CRONTAB", CRONTAB);
	}
	
	public java.lang.String getCRONTAB() {
		return getStr("CRONTAB");
	}

	public void setPROMISC(java.lang.String PROMISC) {
		set("PROMISC", PROMISC);
	}
	
	public java.lang.String getPROMISC() {
		return getStr("PROMISC");
	}

	public void setRPCINFO(java.lang.String RPCINFO) {
		set("RPCINFO", RPCINFO);
	}
	
	public java.lang.String getRPCINFO() {
		return getStr("RPCINFO");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

}
