package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDbTableCount<M extends BaseDbTableCount<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public void setDbTableId(java.lang.String dbTableId) {
		set("DB_TABLE_ID", dbTableId);
	}
	
	public java.lang.String getDbTableId() {
		return getStr("DB_TABLE_ID");
	}

	public void setTableCount(java.lang.Long tableCount) {
		set("TABLE_COUNT", tableCount);
	}
	
	public java.lang.Long getTableCount() {
		return getLong("TABLE_COUNT");
	}

	public void setDateStr(java.lang.String dateStr) {
		set("DATE_STR", dateStr);
	}
	
	public java.lang.String getDateStr() {
		return getStr("DATE_STR");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

}
