package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDbInfo<M extends BaseDbInfo<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public void setDBTYPE(java.lang.String DBTYPE) {
		set("DBTYPE", DBTYPE);
	}
	
	public java.lang.String getDBTYPE() {
		return getStr("DBTYPE");
	}

	public void setUSER(java.lang.String USER) {
		set("USER", USER);
	}
	
	public java.lang.String getUSER() {
		return getStr("USER");
	}

	public void setPASSWD(java.lang.String PASSWD) {
		set("PASSWD", PASSWD);
	}
	
	public java.lang.String getPASSWD() {
		return getStr("PASSWD");
	}

	public void setIP(java.lang.String IP) {
		set("IP", IP);
	}
	
	public java.lang.String getIP() {
		return getStr("IP");
	}

	public void setPORT(java.lang.String PORT) {
		set("PORT", PORT);
	}
	
	public java.lang.String getPORT() {
		return getStr("PORT");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setDBNAME(java.lang.String DBNAME) {
		set("DBNAME", DBNAME);
	}
	
	public java.lang.String getDBNAME() {
		return getStr("DBNAME");
	}

	public void setDbState(java.lang.String dbState) {
		set("DB_STATE", dbState);
	}
	
	public java.lang.String getDbState() {
		return getStr("DB_STATE");
	}

	public void setAliasName(java.lang.String aliasName) {
		set("ALIAS_NAME", aliasName);
	}
	
	public java.lang.String getAliasName() {
		return getStr("ALIAS_NAME");
	}

}
