package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogInfo<M extends BaseLogInfo<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public void setHostName(java.lang.String hostName) {
		set("HOST_NAME", hostName);
	}
	
	public java.lang.String getHostName() {
		return getStr("HOST_NAME");
	}

	public void setInfoContent(java.lang.String infoContent) {
		set("INFO_CONTENT", infoContent);
	}
	
	public java.lang.String getInfoContent() {
		return getStr("INFO_CONTENT");
	}

	public void setSTATE(java.lang.String STATE) {
		set("STATE", STATE);
	}
	
	public java.lang.String getSTATE() {
		return getStr("STATE");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

}
