package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemInfo<M extends BaseSystemInfo<M>> extends Model<M> implements IBean {

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public void setHostName(java.lang.String hostName) {
		set("HOST_NAME", hostName);
	}
	
	public java.lang.String getHostName() {
		return getStr("HOST_NAME");
	}

	public void setVERSION(java.lang.String VERSION) {
		set("VERSION", VERSION);
	}
	
	public java.lang.String getVERSION() {
		return getStr("VERSION");
	}

	public void setVersionDetail(java.lang.String versionDetail) {
		set("VERSION_DETAIL", versionDetail);
	}
	
	public java.lang.String getVersionDetail() {
		return getStr("VERSION_DETAIL");
	}

	public void setCpuPer(java.lang.Double cpuPer) {
		set("CPU_PER", cpuPer);
	}
	
	public java.lang.Double getCpuPer() {
		return getDouble("CPU_PER");
	}

	public void setMemPer(java.lang.Double memPer) {
		set("MEM_PER", memPer);
	}
	
	public java.lang.Double getMemPer() {
		return getDouble("MEM_PER");
	}

	public void setCpuCoreNum(java.lang.String cpuCoreNum) {
		set("CPU_CORE_NUM", cpuCoreNum);
	}
	
	public java.lang.String getCpuCoreNum() {
		return getStr("CPU_CORE_NUM");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setCpuXh(java.lang.String cpuXh) {
		set("CPU_XH", cpuXh);
	}
	
	public java.lang.String getCpuXh() {
		return getStr("CPU_XH");
	}

	public void setSTATE(java.lang.String STATE) {
		set("STATE", STATE);
	}
	
	public java.lang.String getSTATE() {
		return getStr("STATE");
	}

}
