package com.occamedu.security.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePerceptionSource<M extends BasePerceptionSource<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 平台名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 平台名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 对应平台 1-深信服 2-绿盟
	 */
	public void setPerceptionPlatform(java.lang.Integer perceptionPlatform) {
		set("perception_platform", perceptionPlatform);
	}
	
	/**
	 * 对应平台 1-深信服 2-绿盟
	 */
	public java.lang.Integer getPerceptionPlatform() {
		return getInt("perception_platform");
	}

	/**
	 * 协议类型 1-HTTP协议 2-HTTPS协议
	 */
	public void setProtocolType(java.lang.Integer protocolType) {
		set("protocol_type", protocolType);
	}
	
	/**
	 * 协议类型 1-HTTP协议 2-HTTPS协议
	 */
	public java.lang.Integer getProtocolType() {
		return getInt("protocol_type");
	}

	/**
	 * 主机地址
	 */
	public void setHost(java.lang.String host) {
		set("host", host);
	}
	
	/**
	 * 主机地址
	 */
	public java.lang.String getHost() {
		return getStr("host");
	}

	/**
	 * 登录用户名
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	/**
	 * 登录用户名
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}

	/**
	 * 登录密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 登录密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 对应的cookie
	 */
	public void setCookie(java.lang.String cookie) {
		set("cookie", cookie);
	}
	
	/**
	 * 对应的cookie
	 */
	public java.lang.String getCookie() {
		return getStr("cookie");
	}

	/**
	 * 是否通过验证 0-未通过验证 1-已通过验证
	 */
	public void setIsValidated(java.lang.Integer isValidated) {
		set("is_validated", isValidated);
	}
	
	/**
	 * 是否通过验证 0-未通过验证 1-已通过验证
	 */
	public java.lang.Integer getIsValidated() {
		return getInt("is_validated");
	}

	/**
	 * 存储的额外信息
	 */
	public void setExtraData(java.lang.String extraData) {
		set("extra_data", extraData);
	}
	
	/**
	 * 存储的额外信息
	 */
	public java.lang.String getExtraData() {
		return getStr("extra_data");
	}

	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}

	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}

}
