package com.occamedu.security.common.module;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("APP_INFO", "ID", AppInfo.class);
		arp.addMapping("APP_STATE", "ID", AppState.class);
		arp.addMapping("CPU_STATE", "ID", CpuState.class);
		arp.addMapping("DB_INFO", "ID", DbInfo.class);
		arp.addMapping("DB_TABLE", "ID", DbTable.class);
		arp.addMapping("DB_TABLE_COUNT", "ID", DbTableCount.class);
		arp.addMapping("DESK_STATE", "ID", DeskState.class);
		arp.addMapping("HEATH_MONITOR", "ID", HeathMonitor.class);
		arp.addMapping("HOST_INFO", "ID", HostInfo.class);
		arp.addMapping("INTRUSION_INFO", "ID", IntrusionInfo.class);
		arp.addMapping("LOG_INFO", "ID", LogInfo.class);
		arp.addMapping("MAIL_SET", "ID", MailSet.class);
		arp.addMapping("MEM_STATE", "ID", MemState.class);
		arp.addMapping("NETIO_STATE", "ID", NetioState.class);
		arp.addMapping("SYSTEM_INFO", "ID", SystemInfo.class);
		arp.addMapping("SYS_LOAD_STATE", "ID", SysLoadState.class);
		arp.addMapping("TCP_STATE", "ID", TcpState.class);
		arp.addMapping("attack_source_log", "id", AttackSourceLog.class);
		arp.addMapping("boundary", "id", Boundary.class);
		arp.addMapping("command", "id", Command.class);
		arp.addMapping("perception_source", "id", PerceptionSource.class);
		arp.addMapping("shreshold", "id", Shreshold.class);
		arp.addMapping("timer", "id", Timer.class);
		arp.addMapping("timer_command_log", "id", TimerCommandLog.class);
		arp.addMapping("timer_relation", "id", TimerRelation.class);
		arp.addMapping("timer_runner_log", "id", TimerRunnerLog.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_session", "id", UserSession.class);
		arp.addMapping("white_list", "id", WhiteList.class);
	}
}

