package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseAppInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppInfo extends BaseAppInfo<AppInfo> {
	public static final AppInfo dao = new AppInfo().dao();
}
