package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseAppState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppState extends BaseAppState<AppState> {
	public static final AppState dao = new AppState().dao();
}
