package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseAttackSourceLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttackSourceLog extends BaseAttackSourceLog<AttackSourceLog> {
	public static final AttackSourceLog dao = new AttackSourceLog().dao();
}
