package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseBoundary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Boundary extends BaseBoundary<Boundary> {
	public static final Boundary dao = new Boundary().dao();
}
