package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseCommand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Command extends BaseCommand<Command> {
	public static final Command dao = new Command().dao();
}
