package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseCpuState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CpuState extends BaseCpuState<CpuState> {
	public static final CpuState dao = new CpuState().dao();
}
