package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseDbInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DbInfo extends BaseDbInfo<DbInfo> {
	public static final DbInfo dao = new DbInfo().dao();
}
