package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseDbTableCount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DbTableCount extends BaseDbTableCount<DbTableCount> {
	public static final DbTableCount dao = new DbTableCount().dao();
}
