package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseDbTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DbTable extends BaseDbTable<DbTable> {
	public static final DbTable dao = new DbTable().dao();
}
