package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseDeskState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeskState extends BaseDeskState<DeskState> {
	public static final DeskState dao = new DeskState().dao();
}
