package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseHeathMonitor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HeathMonitor extends BaseHeathMonitor<HeathMonitor> {
	public static final HeathMonitor dao = new HeathMonitor().dao();
}
