package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseHostInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HostInfo extends BaseHostInfo<HostInfo> {
	public static final HostInfo dao = new HostInfo().dao();
}
