package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseIntrusionInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntrusionInfo extends BaseIntrusionInfo<IntrusionInfo> {
	public static final IntrusionInfo dao = new IntrusionInfo().dao();
}
