package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseLogInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogInfo extends BaseLogInfo<LogInfo> {
	public static final LogInfo dao = new LogInfo().dao();
}
