package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseMailSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MailSet extends BaseMailSet<MailSet> {
	public static final MailSet dao = new MailSet().dao();
}
