package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseMemState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemState extends BaseMemState<MemState> {
	public static final MemState dao = new MemState().dao();
}
