package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseNetioState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NetioState extends BaseNetioState<NetioState> {
	public static final NetioState dao = new NetioState().dao();
}
