package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BasePerceptionSource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PerceptionSource extends BasePerceptionSource<PerceptionSource> {
	public static final PerceptionSource dao = new PerceptionSource().dao();
}
