package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseShreshold;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shreshold extends BaseShreshold<Shreshold> {
	public static final Shreshold dao = new Shreshold().dao();
}
