package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseSysLoadState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLoadState extends BaseSysLoadState<SysLoadState> {
	public static final SysLoadState dao = new SysLoadState().dao();
}
