package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseSystemInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemInfo extends BaseSystemInfo<SystemInfo> {
	public static final SystemInfo dao = new SystemInfo().dao();
}
