package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseTcpState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TcpState extends BaseTcpState<TcpState> {
	public static final TcpState dao = new TcpState().dao();
}
