package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseTimerRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TimerRelation extends BaseTimerRelation<TimerRelation> {
	public static final TimerRelation dao = new TimerRelation().dao();
}
