package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseTimerRunnerLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TimerRunnerLog extends BaseTimerRunnerLog<TimerRunnerLog> {
	public static final TimerRunnerLog dao = new TimerRunnerLog().dao();
}
