package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseTimer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Timer extends BaseTimer<Timer> {
	public static final Timer dao = new Timer().dao();
}
