package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseTimerCommandLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TimerCommandLog extends BaseTimerCommandLog<TimerCommandLog> {
	public static final TimerCommandLog dao = new TimerCommandLog().dao();
}
