package com.occamedu.security.common.module;

import com.occamedu.security.common.module.base.BaseWhiteList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WhiteList extends BaseWhiteList<WhiteList> {
	public static final WhiteList dao = new WhiteList().dao();
}
